---
- name: Ping google.com
  hosts: localhost  # or specify your target hosts

  tasks:
    - name: Ping google.com
      uri:
        url: "http://google.com"
        return_content: no
      register: result

    - debug:
        msg: "Ping to google.com was {{ 'successful' if result.status == 200 else 'unsuccessful' }}"
